### PR TITLE
Refactoring in login form

### PR DESCRIPTION
**Pull request by SmolenskiyK**

### CODE REVIEW

**Comment by demmy** [comment]
public AuthenticationPresenter Presenter { get { return this.presenter; }  - redundant. We have access to presenter AuthenticationPresenter presenter = null;

please unfy methods - internal void UserIsNotActiveDialog(), internal void AccessDenyDialog() something like
1. add interface like IUserNotify

``` C#
    public interface IUserNotify
    {
        void ShowError(string text, string header);
        void ShowWarning(string text, string header);
        void ShowInfo(string text, string header);
        bool ShowYesNo(string text, string header);
    }
```
1. implement this interface in MainView like

``` C#
        /// <summary>
        /// Informational message that requires user confirmation (OK)
        /// </summary>
        /// <param name="text">message body</param>
        /// <param name="header">message header</param>
        public void ShowInfo(string text, string header)
        {
            XtraMessageBox.Show(text, header, MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        /// <summary>
        /// Message that requires user confirmation or denial (yes/no)
        /// </summary>
        /// <param name="text">message body</param>
        /// <param name="header">message header</param>
        /// <returns>true if yes, false if no</returns>
        public bool ShowYesNo(string text, string header)
        {
            YesNoDialog dlg = new YesNoDialog(text, header);
            return dlg.ShowDialog() == DialogResult.Yes;
        }
```

**Comment by demmy** [comment]
Add to rhis repository WIKI page

**Comment by demmy** [comment]
Use like

``` C#
IUserNotify notifyManager = Programm.MainView();
notifyManager.ShowInfo("Some text", "Some header");
```

**Comment by SmolenskiyK** [comment]
AuthenticationPresenter Presenter { get { return this.presenter; }  is required in Programm.GetAuthUser()

**Pull request merged**
